version: "3.9"
services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: nextchat-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextchat
      POSTGRES_USER: nextchat
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nextchat_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NextChat 应用
  app:
    container_name: nextchat-app
    image: ghcr.io/xiaoshi569/nextchat:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # 数据库配置（必需）
      - DATABASE_URL=postgresql://nextchat:${DB_PASSWORD:-nextchat_password}@postgres:5432/nextchat
      
      # 认证配置（必需，生产环境请修改）
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-32-chars-encryption-key-min}
      
      # 用户注册开关（true=允许注册，false=关闭注册）
      - ALLOW_REGISTER=${ALLOW_REGISTER:-true}
      
      # 可选：代理配置（如果需要）
      - PROXY_URL=${PROXY_URL:-}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app_data:/app/data

volumes:
  postgres_data:
  app_data:
